# Generated by Django 2.0.2 on 2018-02-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район города', 'verbose_name_plural': 'Районы города'},
        ),
        migrations.AlterModelOptions(
            name='enterprise_network',
            options={'verbose_name': 'Сеть предприятий', 'verbose_name_plural': 'Сети предприятий'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': "Связь 'товар-цена'", 'verbose_name_plural': "Связи 'товар-цена'"},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
