# Generated by Django 2.0.2 on 2018-03-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180225_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='city_region',
            new_name='district',
        ),
    ]
