# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180102_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='city_region',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='city_region',
            field=models.ForeignKey(default='Краснодар', on_delete=django.db.models.deletion.CASCADE, to='business.City_region'),
        ),
    ]
