# Generated by Django 2.0.2 on 2018-03-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180310_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='enterprise_network',
            new_name='organization_network',
        ),
    ]
