# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20180102_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='city_region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.City_region'),
        ),
    ]
