# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20180102_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='city_region',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='city_region',
            field=models.ManyToManyField(to='business.City_region'),
        ),
    ]
